### ISSUE TITLE
Add dark mode to the website

### ISSUE THREAD

**Issue by Laxmankohar** [abhishek23012000/covid-19-news#22]
I would like to add toggle button for dark mode to your website.
I am opening this issue under hacktoberfest.
Can you assign it to me?

**Comment by abhishek23012000** [comment]
sure

**Comment by Laxmankohar** [comment]
@abhishek23012000 Check it once then  i will  make a pull request.

![Screenshot (141)](https://user-images.githubusercontent.com/73365025/195075224-afeb0703-1720-46f6-81d1-235abd4ff9d8.png)
![Screenshot (142)](https://user-images.githubusercontent.com/73365025/195075250-43b9722c-f24f-4d58-8f1c-8d53455f3330.png)
![Screenshot (143)](https://user-images.githubusercontent.com/73365025/195075282-5cee6050-dbd1-41d3-832c-7c79e05b800b.png)

**Comment by abhishek23012000** [comment]
make pull request

**Comment by abhishek23012000** [comment]
soo i can accept it

**Comment by Laxmankohar** [comment]
okk
