### ISSUE TITLE
Adding a PageUp Scroll Button

### ISSUE THREAD

**Issue by mgjain9871** [abhishek23012000/covid-19-news#3]
A Pageup Scroll Button is needed for better user experience. 
Please assign me this issue under Hacktoberfest.
@abhishek23012000

**Comment by abhishek23012000** [comment]
> A Pageup Scroll Button is needed for better user experience. Please assign me this issue under Hacktoberfest. @abhishek23012000

ok

**Comment by mgjain9871** [comment]
Please assign me so that i can start working on it

**Comment by deepeshmlgupta** [comment]
Hi, there please assign me this issue so that I can work on it and make the best result that you want.  

> Please assign me so that i can start working on it

make other changes
