### ISSUE TITLE
Fix navbar to the top

### ISSUE THREAD

**Issue by Bishnukt** [abhishek23012000/covid-19-news#42]
The Navbar disappears when scrolled down to other section than home. It would look better if it remains fixed in the top. Shall I make a pr and resolve this one? or If you don't want that, feel free to close this issue.

![Screenshot from 2022-10-21 18-47-09](https://user-images.githubusercontent.com/87633659/197205256-c0ca7734-a60a-46c3-adca-9bbda4e3e15b.png)

**Comment by abhishek23012000** [comment]
ok make pull request
