### ISSUE TITLE
Fixing space between images

### ISSUE THREAD

**Issue by devika6001** [abhishek23012000/covid-19-news#5]
Before:
![WhatsApp Image 2022-10-03 at 8 43 30 PM](https://user-images.githubusercontent.com/87614573/193613137-f0a09ace-0c59-4a6b-b9db-0a0c13454442.jpeg)

After:
![WhatsApp Image 2022-10-03 at 8 43 05 PM](https://user-images.githubusercontent.com/87614573/193613154-4f2f3294-38a9-4aa7-96d8-4f14ccda4d4f.jpeg)

Please assign this issue to me under hactoberfest
@abhishek23012000

**Comment by abhishek23012000** [comment]
make pull request
